### ISSUE TITLE
[interactive fit]: huge & tiny value is not displayed properly on sliders

### ISSUE THREAD

**Issue by konosubakonoakua** [scikit-hep/iminuit#1032]
For example, my limits are listed below.
```python
m_RSq = Minuit(loss_RSq, *initial_params_RSq)
m = m_RSq
m.limits["scale"] = (1e15, 1e20)
m.limits["Ga"] = (1e-18, 1e-16)
m.limits["Rga"] = (1, 200)
m.limits["Ba"] = (1e-18, 1e-16)
```
I do interactive fitting after that.

![image](https://github.com/user-attachments/assets/de1d3ed0-316b-4744-b939-f953ddf0d5a5)

Both major and small values, in my opinion, should be presented in a scientific manner to make them easier to adjust.

**Comment by konosubakonoakua** [comment]
https://github.com/jupyter-widgets/ipywidgets/issues/259

**Comment by konosubakonoakua** [comment]
Or just use floatlogslider
https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#floatlogslider

**Comment by HDembinski** [comment]
These are very good suggestions. I think we want ".4g" instead of ".4e", does that work for your use case?
I don't think that the log slider is a good option. If you have model that is sensitive to a parameter on a log scale, then it is anyway better to the fit the parameter in the log scale than in the linear scale, ie. use x as parameter for the model and use exp(x) in the model implementation.

When we get bounds that can be interactively changed, then we can also adjust the bounds so that a linear slider works well to hit the right values.

**Comment by HDembinski** [comment]
General advice: it is numerically discouraged to use parameters which vary hugely in scale. You can always transform the parameters in your model implementation so that the fitted parameters are within order 1.

**Comment by konosubakonoakua** [comment]
> These are very good suggestions. I think we want ".4g" instead of ".4e", does that work for your use case? I don't think that the log slider is a good option. If you have model that is sensitive to a parameter on a log scale, then it is anyway better to the fit the parameter in the log scale than in the linear scale, ie. use x as parameter for the model and use exp(x) in the model implementation.
> 
> When we get bounds that can be interactively changed, then we can also adjust the bounds so that a linear slider works well to hit the right values.

BTW, should I create a PR for the readout format?

**Comment by HDembinski** [comment]
Yes please
