### ISSUE TITLE
Feature: add scan

### ISSUE THREAD

**Issue by Dapid** [scikit-hep/iminuit#104]
In some very hard cases, I found that a brute force grid search in pyminuit helped Migrad.

https://code.google.com/p/pyminuit/wiki/FunctionReference

Is there any work done to implement this in iminuit? If not, I could give it a try. Something like the scipy version, but with the same interface.

http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.brute.html

**Comment by agbuckley** [comment]
I also needed the PyMinuit scan function and found it missing from iminuit. I don't know if you have something smarter in mind, but here is a quick thing that I cooked up to do that job. First, a generator function to produce iterable N-dimension grid points using the arg format that scan() used:

    def scangrid(*args, **kwargs):
        """
        Generator function which returns lists of parameter (name, value)
        2-tuples via yields (i.e. in a for-expression).

        The arguments are 4-tuples of (name, numpts, low, high) for each
        parameter; the generator iterations will then visit each of the
        lattice points in a grid with num points between low..high in each
        param.
        """
        vec = kwargs.get("vec", [])
        if args:
            # print "@", len(args) #, args
            var, npts, low, high = args[0]
            for val in np.linspace(low, high, npts):
                newargs = args[1:]
                newvec = vec + [(var, val)]
                newkwargs = kwargs
                newkwargs["vec"] = newvec
                for i in scangrid(*newargs, **newkwargs):
                    yield i
                # TODO: in Python3 this can replace the extra for-loop above
                # yield from scan(*newargs, **newkwargs):
        else:
            yield vec

And then an example of it being used to find a brute force minimum:

    def fcn(a,b,c):
        "Some function, i.e. Minuit.fcn"
        return a**2 + b**2 + c**2

    # Find the minimum value of fcn(x) in the grid. Can maybe be done in cool one-liner ways
    scanbest = (None, None)
    gen = scangrid(("a", nscan, amin, amax), ("b", nscan, bmin, bmax), ("c", nscan, cmin, cmax))
    for p in gen:
        x = fcn(**dict(p))
        if scanbest[1] is None or x < scanbest[1]:
            scanbest = (p, x)

    print "BEST FROM SCAN = ", scanbest

From this, dict(scanbest[0]) can be used as starting point arg to the iminuit.Minuit constructor. Seems to work. This could all be bundled into a new method on Minuit if you wanted -- I didn't do it that way since it needs to be done in the Cython definition of the Minuit class, rather than be "appended" to it as a post-hoc method.

Is this any use? It'd be nice to not have to copy this code around to every place where I need to do a simple grid scan before gradient descent!

**Comment by cdeil** [comment]
I think @agbuckley volunteered to contribute this feature to iminuit.

@piti118 - Could you please have a look at his last comment and say if you want this in iminuit and give feedback on API / implementation?

**Comment by cdeil** [comment]
Removing v1.3 milestone. Not many users will use this, and there's no PR, so it shouldn't hold up a release given that we have a ton of good new stuff thanks to @HDembinski .
