### ISSUE TITLE
Github render issue with iminuit HTML output in Jupyter notebooks

### ISSUE THREAD

**Issue by cdeil** [scikit-hep/iminuit#316]
In most notebooks I write that use iminuit, there is a render issue on Github.

Example: https://github.com/iminuit/iminuit/blob/master/tutorial/hard_core_tutorial.ipynb

Screenshot below: note how cell 22 ff is indented in a sub-box, suggesting the issue is in the HTML output from cell 21.

It's not there on nbviewer:
https://nbviewer.jupyter.org/github/iminuit/iminuit/blob/master/tutorial/hard_core_tutorial.ipynb
So it could be a bug in the Github nbconverter or HTML renderer.

But more likely, it's a bug in the HTML output of iminuit for the results table.

If anyone is familiar with notebooks and HTML - please have a look and comment if you think there's something that can be done in the iminuit code that generates the HTML to fix the issue.

![screen shot 2018-10-19 at 14 04 09](https://user-images.githubusercontent.com/852409/47217632-44ae2f80-d3a9-11e8-879c-a2fe8a4f7603.png)

**Comment by HDembinski** [comment]
I checked this on my computer, the problem does not appear there. It also does not appear in the basic tutorial.
https://github.com/scikit-hep/iminuit/blob/develop/tutorial/basic_tutorial.ipynb
I am at a loss why this only happens in the hardcore tutorial.

**Comment by HDembinski** [comment]
There is only one noticeable thing that is different. The line `%%cython --annotate` already produces broken output before the iminuit tables appear, so perhaps the html code gets already messed up there, perhaps some tag is not closed, but it only shows up later when iminuit generates its tables.

It cannot be iminuit's fault, because the basic and the advanced tutorial both render correctly.

**Comment by HDembinski** [comment]
closed in develop

**Comment by cdeil** [comment]
@HDembinski - Thank you!
