### ISSUE TITLE
Raspberry pi issue

### ISSUE THREAD

**Issue by claudiocc1** [scikit-hep/iminuit#319]
First of all: THANK YOU. This is a great product.
I teach a class where the students use raspberry pi's (so that everybody has the same system, and it's cheap).  We use python3.  
The latest version of iminuit (1.3.3) gives me the following error

>>> from iminuit import Minuit
Traceback (most recent call last):
  File "__init__.pxd", line 1011, in numpy.import_array
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa

I guess this is because the rpi is using numpy 1.12.1 which is an old version.

If I install iminuit 1.2, it works.

**Comment by HDembinski** [comment]
Hi Claudio,

thank you for the praise, this keeps us going!

Regarding the error, it looks like iminuit was compiled against a different numpy version than the one that is used when you run your script. I guess you used `pip` to install iminuit. This would suggest that you have at least two versions of numpy installed and `pip` picked the wrong one. Since you are using Python3, did you make sure to also install iminuit with the corresponding `pip3`?

You could also try to install with `conda`. The latter gives you a consistent environment where things are more likely to work together correctly, because they are automatically tested. With `pip`, it is much harder for us to make sure that the package works under all possible conditions.

**Comment by claudiocc1** [comment]
hi Hans,

yes, I installed with pip3.

The issue is that the recommended version of numpy on raspbian currently
is 1.12.1, which is old, see
http://www.raspberryconnect.com/raspbian-packages-list/item/87-raspbian-python

It is a (basically) solved problem in that I can make it work by using an older
version of iminuit (1.12) or by installing with conda (I did the first, not the second).

No idea how hard it is to implement dependencies in pip/pip3.
Maybe you could add a line in the documentation with a warning for the 
users of raspbian (I realize that it  is a small community...).

Thanks again, and keep up the great work.

C.

**Comment by HDembinski** [comment]
If you are ok with the older version of iminuit, that's great. I don't see why iminuit shouldn't work with an older version of numpy as well. In fact, if the version of numpy was the problem, you should already get an error during compilation when you install with pip, not later when you try to import iminuit.

I am open to adding an explanation in the docs, but first I want to be sure that I understand the problem.
