### ISSUE TITLE
How to communicate variable-limits which depend on each other?

### ISSUE THREAD

**Issue by relleums** [scikit-hep/iminuit#366]
In the [tutorial](https://nbviewer.jupyter.org/github/scikit-hep/iminuit/blob/master/tutorial/basic_tutorial.ipynb) it is shown how to communicate the limits of a variable. For variables ```a``` and ```b```, I can set up a "rectangular" space to be searched using the keywords ```limit_a=(-1, 1)``` and  ```limit_b=(-1, 1)```.

But how can I communicate that the limits of ```a``` and ```b``` depend on each other, i.e. that the searched space is not rectangular but e.g. has a disk-like perimeter which requires  ```sqrt(a**2 + b**2) <= 1 ```?

In a particular case I ran into lately, I did not even have an analytic expression for the limits dependencies. But I was able to give a second function, taking the same parameters as my first function to be minimized, which only indicates in a boolean way whether my variables are within the limits. 

Does such a feature exist for MINUIT?
If not, does such a feature make sense for MINUIT, or is there a different way of having this feature?

**Comment by relleums** [comment]
One solution is of course to transform into a variable-space with no correlations in the limits, such as azimuth-angle ```t``` and radius ```r``` for my minimal example with positions  ```a``` and ```b``` on a disk-like surface. But sometimes such a transformation is not obvious to find. Further, such transformations might induce singularities for e.g. ```r = 0``` which I assume do not help finding the minimum.

**Comment by relleums** [comment]
This is a comment I received by long year MINUIT user Werner Hofmann:

He suggests to add an artificial limits-wall onto the actual function to be minimized which lets the function's response grow quickly when approaching the correlated limits.

I will try this. Does this sound like good practice to you guys?

**Comment by HDembinski** [comment]
MINUIT only handles what is called box constrains, meaning that the limits on the parameters must be constant and independent. This is a fundamental limitation of the algorithm. If you have limits that depend on each other, you have three options (two you mentioned):

1) Use another minimizer to locate the minimum which supports complex boundaries. I successfully used nlopt to solve difficult optimization https://nlopt.readthedocs.io/en/latest. Once the minimum is found and if it is not near the boundary, make box-constraints around the minimum and run iminuit to get the uncertainties (make sure that the box-constraints are not too tight). nlopt cannot give you the uncertainties.

2) Change the variables so that the limits become independent, such as going from x,y to r, phi for a circle. This is not always possible or desirable, of course.

3) Artificially increase the negative log-likelihood in the "unphysical region". This is not as easy as it sounds.

The third method done in a non-ad hoc way leads to augmented lagrangian algorithm https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/#augmented-lagrangian-algorithm
I think that this algorithm could be used with MINUIT, but I haven't looked at it in detail.

So in practice, I would recommend trying 2) first, and if that does not work, try 1) or 3). You should be aware that the errors obtained with MINUIT will be nonsense if the minimum found by MINUIT is near the artificial increase of the likelihood. You further need to make sure that this artificial increase is analytical, because iminuit uses a gradient-based algorithm. You cannot insert step functions into the likelihood, this this will make MINUIT very unstable.

**Comment by HDembinski** [comment]
This should be added to our FAQ...

**Comment by HDembinski** [comment]
What you actually want is the https://en.wikipedia.org/wiki/Interior-point_method. I added this answer to the FAQ in the develop branch.
