### ISSUE TITLE
Strategy / tolerance keyword arguments for Minuit constructor

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/iminuit#466]
It would be convenient to allow setting the `strategy` and `tol` through keyword arguments when initializing Minuit via `iminuit.Minuit()` and `iminuit.Minuit.from_array_func()`. This could allow propagating these parameters through the `pyhf` optimizer API after the upcoming refactoring (https://github.com/scikit-hep/pyhf/pull/951).

Tagging @kratsg who can provide more details on why this is very useful for `pyhf`.

related comment: https://github.com/scikit-hep/iminuit/issues/353#issuecomment-504356722

**Comment by HDembinski** [comment]
It is no problem to do that, but I wonder: what's the benefit over doing this via the attribute?

**Comment by kratsg** [comment]
It would generally make more sense if it was either from the constructor or through the `migrad(....**kwargs)` call instead. At least to sort of unify alongside what `scipy.optimize.minimize` does with similar configurations?

**Comment by HDembinski** [comment]
`strategy` and `tol` affect also Minos and Hesse.

**Comment by HDembinski** [comment]
scipy.optimize.minimize is a functional paradigm, while iminuit follows a OOP paradigm. It is a different design that follows different rules. I cannot remove `.strategy` or `.tol`, since users may want to change these attributes at any time and adding more keywords to init would add a redundant way of setting strategy or tol. Redundancy is bad.

**Comment by alexander-held** [comment]
What is the difference between strategy/tolerance and e.g. `errordef` or `print_level`, which can be set through both the constructor and `.errordef` / `.print_level`?
