### ISSUE TITLE
CUDA and iminuit through cupy? Not an issue, an advice request.

### ISSUE THREAD

**Issue by RDeRenzi** [scikit-hep/iminuit#649]
Sorry if I bother you. First of all I am using iminuit to great advantage and I am very grateful. 

I am analysing muon spin spectroscopy data with large number of DoFs & parameters, eg  when trying to perform global fits over many datasets, typically experiments varying temperature. I find  no constraint in iminuit itself, but in practice my code times out.

CUDA on GPUs would be a solution, and I am reading of cupy. https://cupy.dev/

Is this feasible? Is it in your plans? Or do you have alternative plans in mind to the same end.

Thanks a lot for any feedback.  

Best regards Roberto

**Comment by HDembinski** [comment]
> Sorry if I bother you. First of all I am using iminuit to great advantage and I am very grateful.

Great to hear this! :) Btw, you can also chat on gitter with us https://gitter.im/Scikit-HEP/iminuit

The idea of a low-level package like iminuit is to give users like you all the freedom to implement the cost function in any way you like, also based on a computation that uses cupy, for example. We provide some CPU-based cost functions, but the idea is that you can just write your own. If you write a cost function that runs on the GPU, I am happy to include it to iminuit, but currently we only have CPU-based ones. This is also because I don't have a computer to interactively test GPU computations, my development machine does not have a suitable graphics card.

**Comment by HDembinski** [comment]
https://github.com/scikit-hep/pyhf maybe something that suits you if you do binned fits, they also support GPU acceleration through the frameworks they use.

You can also give [numba](https://numba.pydata.org), which allows you to run code on the GPU.

**Comment by HDembinski** [comment]
I am closing this but feel free to reopen if you have found an issue preventing you from using cupy, but I don' think there is one.

**Comment by AndreV84** [comment]
[BD_minuit_minimization_for_GPU.txt](https://github.com/scikit-hep/iminuit/files/10046426/BD_minuit_minimization_for_GPU.txt)
 a colleague asks how to migrate this to c++ gpu cuda minuit implementation from iminuit
Could you add on it, please?
[H_All.txt](https://github.com/scikit-hep/iminuit/files/10046422/H_All.txt)

**Comment by AndreV84** [comment]
@HDembinski

**Comment by HDembinski** [comment]
Since you can use any cost function with iminuit, you can also use one that uses cupy internally.

What kind of fit do you want to do?
