### ISSUE TITLE
Specifying relationships between fit parameters

### ISSUE THREAD

**Issue by mdaeron** [scikit-hep/iminuit#964]
Apologies if I'm beating a dead horse here, or if I missed some obvious piece of documentation.

I'm new to iminuit and looking into how/whether it allows arbitrary constraints of fit parameters. If I understand correctly, I may [fix the value of a parameter to a constant floating number](https://iminuit.readthedocs.io/en/stable/reference.html#iminuit.Minuit.values) using the `Minuit.fixed` property. Based on #638 it seems that constraining parameters as functions of other parameters (e.g., `param2 = 2*param1`) is not supported and will not be? Is that due implementation/complexity cost or because such a feature is considered out of scope? #638 seems to suggest the latter, but one could argue that fixing parameters to a function or to a constant are not conceptually different (although quite different to implement, granted).

FWIW I believe non-constant constraints on parameters is a killer feature in many use cases. Writing a bespoke cost function instead works when one is writing the whole code, but is not really an option when the end-user is using a library that they didn't write. In that case it's extremely powerful to provide simple hooks specifying relationships between parameters.

Whatever the case, thanks for your work on iminuit. It looks pretty powerful and I'll keep looking into it.

**Comment by HDembinski** [comment]
In Minuit itself, you can
* Fix parameters to constant values `Minuit.fixed`
* Constrain parameters to an interval `Minuit.limits`
* Use penalty-terms to soft-constrain a parameter with `iminuit.cost.NormalConstraint`

In the context of fitting, it does not make sense to have `param2 = 2 * param1`, because then `param2` is not a parameter anymore, it is determined by `param1`. You can implement "constraints" like this in your model.

```py
def model1(x, param1, param2):
    return x * param1 + param2


def model2(x, param1):
    return model1(x, param1, 2*param1)

# proceed to fit model2 instead of model1
```
